insert into recipes
       values
(nextval('for_id_recipes'), 'yummy n  easiest  warm blueberry sauce', 20, 222, 'serve it liberally on pancakes, ice creams or just have a spoonful of it any time!', '[`place all ingredients in a saucepan`, `bring to a boil`, `reduce the heat and simmer for 5 minutes`, `yum , it is ready !`]'),
(nextval('for_id_recipes'), 'any type  nut butter', 15, 291, 'easy to make and very adaptable.  great on canapes, breads, beef or chicken.', '[`cream butter in a small bowl with an electric mixer`, `transfer to blender or food processor`, `add remaining ingredients and blend well`, `place butter in plastic wrap and form into a log shape or place in a ramekin and cover tightly`]'),
(nextval('for_id_recipes'), 'death by chocolate  copycat dark chocolate sauce', 5, 155, 'we were astonished to discover that we could make a dark chocolate sauce in minutes for pennies that matched what we`d received in a $4, 6-ounce gift jar.', '[`mix cocoa and sugar thoroughly`, `stir in water in small amounts , until desired consistency is reached`, `keep in tightly sealed container in refrigerator`, `best served on second day , to make sure sugar completely dissolves`]'),
(nextval('for_id_recipes'), 'sweet dreams  shake', 10, 111, 'my sister received this recipe from a friend, because she was having trouble falling asleep at night. the friend told my sister if she drank this shake before going to bed, it would help her fall asleep. my sister swears by it! i don`t have trouble falling asleep, so i can`t say if it really works, but it taste great! :)', '[`mix all ingredients in a blender until well blended`, `serve immediately`]'),
(nextval('for_id_recipes'), 'leftover  rice pudding', 30, 230, 'uses leftover rice and is egg-free. inspired from a community cookbook.', '[`combine all ingredients in a saucepan`, `heat over medium-high and stir often until milk and rice thicken , about 20 minutes or so`, `put into dessert cups and chill until ready to eat`]'),
(nextval('for_id_recipes'), '2 minute noodles for two with ham   cheese', 20, 227, 'a quick tasty way i serve 2-minute noodles. this makes a generous serve for two, it would be enough for a family of four as a light meal / snack.', '[`hard boil eggs and let sit in cold water for 5 minutes before peeling and cutting into 6-8 slices`, `cook noodles for 2 minutes in boiling water then drain liquid and add in flavour satchets from 2 of the packets`, `gently mix cheese , ham and sliced egg into the noodles and serve immediately`]'),
(nextval('for_id_recipes'), '3 vegetable casserole', 50, 135, 'my bosses wife swears by this recipe for leftovers. i have used it many times, make a good meal or sidedish.', '[`scald milk with margarine`, `remove from heat , add bread veggies , salt , eggs and 3 / 4 cup cheese`, `mix together and pour into a 4 quart greased casserole , top with remaining 1 / 2 cup of cheese`, `bake at 325 for 40 min`, `want some extra flavour use half evaporated milk`]'),
(nextval('for_id_recipes'), '30 second sandwich', 2, 209, 'its fast and easy after a night on the tiles', '[`put the cheese between the two slices of bread and microwave for 30 seconds`]'),
(nextval('for_id_recipes'), 'absolutely fail proof easy marmalade', 30, 63, 'this recipe was printed in the jerusalem post last week, and it`s from lynette levius of netanya, israel. i haven`t tried it yet, but plan to make a batch this weekend.  february 2010:  since posting this recipe i`ve made it several times each winter (winter is citrus seaon here).  it`s a wonderful recipe, totally fail-proof as the title says.  it`s great on toast and makes a wonderful gift.  i especially love a 50/50 orange/clementine mix, a rich citrus flavor with an intense orange color.', '[`take the 6 citrus fruits and wash well , removing any blemishes`, `cut into quarters , and place in a food processor`, `chop until finely ground , skin and all`, `for an optional extra add some crystallized ginger`, `boil with the 1 kilo of sugar , stirring occasionally with a wooden spoon , for 20 minutes`, `it splatters , so be careful`, `this quantity fills about 5 x 340 gram jars`, `do not double the ingredients , rather make two batches`, `it never goes dark and lasts for up to 6 months in the refrigerator without the need to sterilize the bottles`]'),
(nextval('for_id_recipes'), 'acadia s asparagus side with dill', 11, 55, 'i love asparagus and dill so i decided to create a easy side dish tonight utilizing both.', '[`break woody ends off of each asparagus by snapping them to break at natural break`, `arrange asparagus in a steamer basket over boiling water and steam covered for 4 - 5 minutes or until crisp tender`, `in a skillet add 1-tablespoon butter and after it melts add asparagus and dill`, `lightly saute for 1 minute`, `serve and enjoy !`]'),
(nextval('for_id_recipes'), 'adam carolla s famous thanksgiving cranberry sauce recipe', 11, 40, 'adam says, “cranberry sauce is the unsung hero of thanksgiving…it bridges the gap between all other foods” here is the recipe he used to give out on the air every thanksgiving. this differs from the recipe on the ocean spray cranberry bag because it call for less sugar.', '[`rinse cranberries`, `bring water and 1 / 2 cup sugar to a boil`, `add cranberries and cover`, `let simmer for about 5-10 minutes`, `add more sugar to taste , if desired`]'),
(nextval('for_id_recipes'), 'aelplermagronen  swiss pasta', 30, 169, 'this is how the aelplermagronen are prepared in the [swiss] canton of unterwalden. in uri, the potatoes are left out.', '[`peel and dice the potatoes`, `boil in salted water`, `add the noodles shortly before the potatoes are done`, `the potatoes should be soft`, `drain and arrange in alternate layers with the cheese in a deep baking dish`, `pour in the cream and place in the hot oven for a few minutes until the cheese melts`, `meanwhile , melt the butter in a skillet`, `slice the onions and saute until they turn light brown`, `spread over the noodles and potatoes`, `serve with apple puree or salad`]'),
(nextval('for_id_recipes'), 'agnes creamy rice pudding', 40, 167, 'this is a great creamy stove top version of rice pudding. i like it while it`s still warm, but it`s great cold too.', '[`combine rice , water , salt , and butter in a pan`, `cover and simmer for 15 minutes`, `at the same time , heat the milk to scalding`, `stir hot milk into rice , add raisins if using , cover , and simmer 15 more minutes`, `beat eggs and sugar together`, `add some of the hot mixture to them , stirring constantly`, `return egg mixture to rice mixture and cook 5 minutes , stirring constantly`, `it should start to bubble`, `pour into a bowl`, `add the vanilla`, `cool`]'),
(nextval('for_id_recipes'), 'alcohol free basic eggnog', 1455, 138, 'from the jerusalem post', '[`separate room temperature eggs`, `beat yolks with half the sugar until creamy`, `beat whites with half the sugar until peaks hold`, `beat cream until stiff`, `fold everything together`, `add vanilla to taste`, `refrigerate in covered container at least 24 hours`, `put in serving bowl , sprinkle with nutmeg`]'),
(nextval('for_id_recipes'), 'allspice substitute', 5, 279, 'this is one spice that i do not normally have on hand.  most of my recipes do not call for it, but sometimes you just need it.  this is a recipe for a substitution that works great.  below are two measurements.  the normal formula is equal amounts of all three, but if you like the cloves and nutmeg less predominant, use the lesser amount.  both will have the flavor of allspice.  see note at the bottom.', '[`mix together`, `you want equal amounts of the spices above or`, `use according to your recipe`]'),
(nextval('for_id_recipes'), 'almond milk  almond drink base', 5, 170, 'you can make this at home, it`s easy and heart healthy! it makes a geat base for smoothies and sauces. nuts are used prolifically in africa and asia.', '[`add ingredients to blender`, `process at low speed for 1 minute , and 3 minutes at high speed until smooth`, `strain the mixture through cheese cloth to remove remaining solids`, `refrigerate until ready to use`]'),
(nextval('for_id_recipes'), 'amanda s cinnamon toast', 4, 174, 'cinnamon toast is not just for kids. enjoy it for breakfast or a snack. this is my after school snack.', '[`mix cinnamon and sugar together`, `spread butter on warm , toasted bread`, `sprinkle cinnamon / sugar mixture over buttered bread`, `enjoy !`]'),
(nextval('for_id_recipes'), 'amber onions', 80, 147, 'a simple but impressive recipe from my mother, charlotte white. the honey accentuates the natural carmelization of the onions, and the catsup (surprise secret ingredient!) lends color as well as flavor.', '[`combine first five ingredients in a shallow baking dish`, `peel the onions and cut in half through the equator`, `place cut-side down in baking dish`, `cover tightly`, `bake at 350 for 1 hour or until very tender`, `turn onions cut-side up and baste with sauce from bottom of pan before serving`]'),
(nextval('for_id_recipes'), 'amish style french toast  breakfast is served', 15, 132, 'great breakfast! kids love it, and it`s a nice variation between pancakes and toast. enjoy!', '[`beat all ingredients , except bread , together`, `preheat frying pan`, `dip bread into milk mixture and place in hot frying pan`, `pour leftover milk mixture on top of the bread`, `fry on both sides until brown`, `serve with peanut butter and syrup`]'),
(nextval('for_id_recipes'), 'amish mennonite   meadow  tea for freezing', 45, 52, 'my mennonite grandmother`s recipe for `meadow` tea - keeps well all winter long! yummy! enjoy!', '[`boil 4 quarts of water`, `add 1 quart tea stems and leaves`, `bring to a boil`, `turn off the heat , and steep for 1 / 2- 1 hour , pressing tea down in water periodically`, `remove leaves and stems`, `strain through cheesecloth`, `add 4-6 cups sugar`, `stir until dissolved`, `place in freezer boxes , cool completely and freeze`, `to prepare: mix 1 concentrate plus 2-3 concentrate boxes full of water and serve !`]'),
(nextval('for_id_recipes'), 'and the beet goes on', 10, 41, 'the beet is one of the most nutritious vegetables. a good source of vitamin c, k, folate, and magnesium. paired with carrots and celery, it`s a good cancer preventitive. also good for the unrinary tract and ulcers.', '[`wash and trim vegetables`, `juice carrots and celery first , then juice beet`, `stir and drink ! enjoy !`]'),
(nextval('for_id_recipes'), 'apple and carrot tzimmes  pareve', 135, 173, 'from high tech jewish cooking.  haven`t tried this one yet.  it`s a vegetable (and fruit) side dish. i`ve had tzimmes with chunks but this one has shredded apples and carrots which makes it a bit different.', '[`insert shredding disc in food processor and shred apples and carrots`, `put all ingrdients into saucepan`, `cover and cook over low heat for 2 hours , or until tender`, `stir occasionally , adding more water if necessary`, `serve hot`]'),
(nextval('for_id_recipes'), 'apple and carrots juice', 5, 48, 'an apple a day! this is the basic juice that you can add any veggie you like. this base is sweet and healthy. be sure to use organic produce.', '[`alternating carrots and apples push through the hopper`, `to your health !`]'),
(nextval('for_id_recipes'), 'apple bites', 5, 189, 'a delicious, incredibly easy way to dress up fresh apples for an quick snack.  enjoyed by both kids and adults alike.', '[`cut up apple into bite sized chunks`, `put the chopped apple into a container with a lid`, `sprinkle on the cinnamon , put the lid on the container , and gently shake so cinnamon covers apple`, `eat and enjoy immediately`]'),
(nextval('for_id_recipes'), 'apple pie potpourri  non food', 485, 183, 'when peeling apples for cooking/baking/snacking, don`t discard the peels.  instead, multi-purpose them to make this aromatic potpourri that smells like a freshly-baked apple pie.  use it as a real estate selling tactic, to set the mood for a party or simply for your own enjoyment.  it`s easy to make and all-natural.', '[`into a small crock pot , place apple peels , cloves , cinnamon and nutmeg`, `pour water over all`, `set on low heat for the entire day , checking the water level periodically to prevent burning`, `you can even enjoy it for one more day if you like`, `just place the cooled mixture into a container , refrigerate and reheat another day`]'),
(nextval('for_id_recipes'), 'apple rabdi', 40, 69, 'one of my favourite dessert. the sugar when replacd with sugar substute is a good delicacy for diabetics.', '[`boil the milk in a big pan and simmer till it becomes half`, `add the sugar and apples and cook for sometime`, `serve hot or chilled`]'),
(nextval('for_id_recipes'), 'apple banana fruit leather', 455, 62, 'it`s a good flavor.', '[`blend ingredients in blender until pureed`, `dry in dehydrator for 7 1 / 2 hours at 125 degrees`]'),
(nextval('for_id_recipes'), 'apple orange blend juice', 15, 51, 'fresh apple, orange, pear and lemon prepared in your juicer. the lemon cuts the sweetness of the juice.', '[`wash apples , pear and lemon`, `core apples and pear`, `discard cores`, `peel orange`, `discard peel`, `cut lemon , leaving peel on`, `turn juicer on and put fruit through the juicer chute`]'),
(nextval('for_id_recipes'), 'applesauce  using only apples  to freeze', 35, 49, 'this recipe is so simple i hesitate to post it. it is such a staple at our house, just thought others might like to try this method. a rotary food press (or food mill) is needed for this this ', '[`place unpeeled apples and water in a large heavy bottomed pot`, `cover and place over low-med heat , stirring occassionally`, `when apples are soft and still hot , run through a food mill placed over a bowl`, `to freeze: cool place in quart ziplock bags and freeze`, `makes about 4 quarts`]'),
(nextval('for_id_recipes'), 'applesauce salad', 10, 199, 'this recipe is from farmer`s almanac', '[`mix all ingredients together`, `serve hot or cold`]'),
(nextval('for_id_recipes'), 'artichoke hearts wrapped in bacon', 13, 305, 'an appetizer from dr. and mrs. atkins. (quick & easy new diet cookbook)', '[`preheat the broiler`, `cut the bacon slices in half , place on a baking sheet , and broil for 3 minutes`, `let the bacon cool enough to handle`, `wrap each artichoke half in a piece of bacon , broiled side facing inward , and secure with a toothpick`, `broil 4 to 5 minutes , or until the bacon is brown and crisp`]'),
(nextval('for_id_recipes'), 'artichokes for pressure cooker', 13, 37, 'perfect artichokes, ready in just 8 minutes!  from cuisinart recipe booklet', '[`place 1 cup of water with the juice of one lemon in the cooking pot`, `prepare artichokes`, `cut stem off at base , cut 1 / 3 off the top , and trim off outer layers of tough leaves`, `(optional step is to open up leaves at the top and remove the choke with a melon baller or spoon`, `rub the cut parts of the artichoke with the remaining lemon halves`, `place them top down in the pot`, `lock lid in place`, `set for 8 minutes at high pressure`, `serve immediately with melted butter or your favorite dipping sauce`]'),
(nextval('for_id_recipes'), 'artichokes steamed in the microwave', 16, 42, 'i love fresh artichokes but did not like how long they took to steam until i discovered this procedure. 3 artichokes done in 11 minutes! how easy and quick is that!? this can also be a prelude to grilled or roasted artichokes if you steam half the amount of time in the microwave and then proceed with the other recipes. great timesaver!', '[`trim the artichokes by cutting off the stem and cutting off the`, `i often cut them in half , lengthwise , and scoop out the choke but you can skip this step`, `rub the lemon over all the cut parts of the artichokes so it does not brown`, `place all 3 of the artichokes upside down in a microwaveable dish with a tight fitting lid`, `try a dinner or salad plate on top of your dish if you do not have a lid that exactly fits`, `i place them upside down so the water is not collected in the artichokes but they can be placed right side up and then squeezed out later`, `add the water and cover`, `cook on high for 11 minutes`, `check at about 9 minutes since all ovens are not the same , and pierce the hearts with a fork`, `if they are soft they are done`, `drain and serve`]'),
(nextval('for_id_recipes'), 'asparagus in hazelnut butter sauce', 35, 151, 'a very simple but elegant vegetable side dish. works especially well with beef.', '[`preheat oven to 400f`, `arrange asparagus in casserole dish`, `sprinkle with hazelnuts`, `top randomly with pats of butter`, `bake for 30- 45 minutes`]'),
(nextval('for_id_recipes'), 'aunt frances  lemonade', 10, 51, 'the combination of fruits was a sweet and tangy blend my children love. easy to throw together and quickly gone. this reminds me of the five alive frozen concentrate i enjoyed growing up.', '[`squeeze the juice from 4 each of the lemons , limes and oranges and pour into a gallon size pitcher`, `thinly slice remaining fruit and set aside for garnish`, `add water and sugar to juice and mix well`, `store in the refridgerator`, `serve on ice with fruit slices`]'),
(nextval('for_id_recipes'), 'aunt lois  butter roll', 35, 214, 'i found this quick, easy recipe on cooks.com and it is the old fashioned version of the ever-so-famous southern dessert, butter roll--enjoy!', '[`roll out biscuits as thin as possible on floured board`, `spread each one with butter and sprinkle with sugar and a little nutmeg`, `roll up like jelly roll`, `place rolls into a buttered casserole dish`, `topping: mix the 3 / 4 cup sugar , 2 cups milk and the vanilla`, `pour over rolls`, `bake at 350 degrees until brown`, `serve warm`, `the rolls may be made from any biscuit dough recipe`]'),
(nextval('for_id_recipes'), 'aunt rosella s banana salad', 15, 90, 'this is dated 1983 in my mom`s cookbook and attributed to my lovely aunt rosella--where she got the recipe, we don`t know. i remember eating this as a kid and loving it. wonderful use of bananas', '[`chop peanuts`, `mix egg , sugar , water , and vinegar`, `put in heavy saucepan`, `heat until low boil , stirring constantly until thickened`, `cool`, `cut each banana in half and peel`, `now slice each in half again`, `place on platter sliced sides up`, `cover bananas with sauce and sprinkly with chopped peanuts`]'),
(nextval('for_id_recipes'), 'auntie s milk punch', 2, 163, 'i got this recipe from the the black kettle (punta clara) cookbook. tastes sort of like a snow cream!', '[`put ice in shaker with remaining ingredients`, `shake until foamy and completely chilled`, `serve immediately`]'),
(nextval('for_id_recipes'), 'autumn holiday tea', 4, 183, 'nice, warming autumn drink!', '[`mix ingredients well and store in air tight container`, `boil milk for mug of tea`, `add 1 plain tea bag per mug , pour hot milk over teabag in mug , sprinkle a pinch or two of dry mixture into hot milk and teabag`, `stir`, `leave teabag in mug`, `if you really like this , you can always make more of the dry ingredients , just make sure its in equal amounts`, `you can always add a little extra sugar in tea if you like it sweeter`]'),
(nextval('for_id_recipes'), 'avocado banana smoothie', 3, 99, 'a creamy delicious  drink that taste super good', '[`put avocado , banana , milk , sugar , put in to a blender`, `mix the ingredients with blender and enjoy :)`]'),
(nextval('for_id_recipes'), 'bacon and egg cups', 25, 192, 'this is a simple recipe that my husband makes for us a lot for breakfast.  just takes one pan and you have bacon and eggs! this recipe easily adapts to how many you want to make, just use more muffin/cupcake pans!  now if you like to have your bacon crispy, this will not be for you.  the bacon gets done but not crispy! the bacon flavors the egg, which is much like a poached or boiled egg. the servings are based on two bacon and egg cups per person. hope you enjoy!', '[`preheat oven to 350 degrees`, `pre- cook bacon for 5-10 minutes`, `using a muffin / cupcake pan , line the holes with a slice of bacon , pressing the bacon around the sides of the hole , not on the bottom`, `crack one egg into each hole`, `sprinkle with salt and pepper and cheese if desired`, `bake at 350 degrees for 20 minutes or until the egg is the doneness you like`, `these bacon and egg cups should pop right out of the pan`]'),
(nextval('for_id_recipes'), 'bacon  banana   cheese toasted fingers', 15, 365, '20 years ago i worked the graveyard shift in a hotel restaurant in town.  this was one of the most popular items on the menu with the late night drinkers.', '[`cook bacon under a grill until crispy`, `toast bread and then butter it while hot`, `place bacon on top of toast`, `slice banana and place on top of the bacon`, `then top with cheese`, `place under the grill until golden and bubbly`, `slice into 3 fingers and serve`]'),
(nextval('for_id_recipes'), 'bacon wrapped cheddar egg bites', 35, 192, 'it`s an omelet muffin wrapped in bacon!', '[`preheat oven to 375`, `spray muffin tin`, `line each spot with a bacon around the edges`, `whip all eggs`, `mix in cheese and other desired toppings`, `evenly pour the egg mix into each spot , filling about 1 / 2 way or 3 / 4 way`, `bake about 25 minutes or until bacon is cooked`, `pop out and enjoy !`]'),
(nextval('for_id_recipes'), 'bag of pudding', 5, 74, 'i got this recipe from recipe goldmine, and my daughter and i made it together. she thinks it`s hilarious. it`s so simple, a child can do it alone.', '[`measure pudding powder into ziploc type bag`, `add milk`, `seal bag , squeezing out excess air`, `knead gently until well mixed and thickened`, `if your hands are warm , you may need to refrigerate for a few minutes`, `when thickened , snip a small hole in one corner and squeeze the pudding directly into your mouth !`]'),
(nextval('for_id_recipes'), 'baked apple custard', 85, 142, 'easy traditional custard with a difference that children like. recipe source: bon appetit (november 1981)', '[`melt butter in a large skillet over medium-high heat`, `add apple slices and saute for 1 minute`, `reduce heat to medium-low , cover and cook 1 minute longer`, `reduce heat to low , uncover and let apples cook until light brown`, `set aside`, `preheat oven to 325-degrees f`, `butter 6 custard cups`, `in a bowl , whisk eggs until thick`, `add sugar and salt and beat well`, `blend in milk and vanilla`, `pour custard into prepared custard cups`, `set custard cups into large shallow baking pan`, `add enough boiling water to pan so water comes up halfway up sides of cups`, `bake for 1 hour or until a knife inserted in center of custard comes clean`, `remove cups from water and let cool to room temperature`, `top each custard with 4 overlapping apple slices`, `refrigerate until cold or overnight`, `sprinkle with nutmeg before serving`]'),
(nextval('for_id_recipes'), 'baked apple for one', 22, 166, 'this smells delicious while it bakes. it can easily be multiplied to accomodate a larger family. if you use a cold apple, the sugar will stick to the outside nicely, but it will take longer to cook. i have heard of people using honey instead of sugar, but it tastes funny to me.  (note:  i`m sorry i originally forgot to post the baking temperature of 375)', '[`preheat the oven to 375`, `place the apple in a small oven safe bowl or dish`, `spoon the liquid into the dish beneath the apple`, `layer the sugar , raisins , and cinnamon in the center of the apple , sprinkling the excess sugar over the top`, `cover the entire dish with foil and bake until tender , about 20 minutes`, `it can safely be eaten 5 minutes out of the oven`]'),
(nextval('for_id_recipes'), 'baked citrus apples and pears', 50, 135, 'this is a healthy dessert ideal for using up pears, apples, oranges and lemons that may be left in the fruit bowl. serve warm as a light dessert with greek yoghurt, or eat chilled with a bowl of granola for a healthy start to the day. this recipe is also good for children!', '[`preheat the oven to 350f`, `place the pear and apples quarters in a flameproof dish with the cinnamon stick , nutmeg , raisins , lemon and orange juice with the zest strips`, `cover the dish with foil and bake in the oven for about 35-40 minutes or until the fruit is just soft`, `serve warm with creme fraiche or yogurt`]'),
(nextval('for_id_recipes'), 'baked corn on the cob', 35, 152, 'one of my neighbors was telling me this is her favorite way to make corn. she bakes the corn in the husk and then peels it back and uses the husk as a handle. *posted corn as two ingredients because that is the only way food would take it.', '[`in an oven heated at 350 f , cook corn in husk for 25 minutes`, `after taking corn out of oven , let it cool for 5 minutes , and then pull husk layers down , leaving them attached to the base of the cob , which can act as a handle`]'),
(nextval('for_id_recipes'), 'baked cranberries', 65, 65, 'this recipe has got to be at least 60 years old. im definatly making it this thanksgiving, got to be a cranberry lover for this one.', '[`arrange berries in baking dish`, `sprinkle with sugar`, `cover closely`, `bake at 350 degrees for 60 minutes`, `do not overbake !`]'),
(nextval('for_id_recipes'), 'baked custard cups', 50, 133, 'easy homemade custard, yummy! serve with fresh fruit.', '[`combine first 5 ingredients , stir until blended`, `slowly add scalded milk , stirring constantly`, `pour into 4 custard cups`, `set cups in 9x9 inch baking pan`, `pour 1 inch hot water into pan`, `bake at 350 for 35 minutes , or until knife comes out clean`, `remove from pan , cool`, `chill`]'),
(nextval('for_id_recipes'), 'baked egg custard', 15, 48, 'a comfort food can also be used as a vanilla pie filling.', '[`bring milk just to a boil and add beaten eggs and remaining ingredients`, `whisk well`, `pour into a buttered casserole dish and bake in a 350 preheated oven for 30 minutes`, `enjoy`]');


insert into recipes_content_products
  values
(2, 799, 112, 'g'),
(2, 1155, 66, 'g'),
(2, 115, 22, 'g'),
(2, 131, 88, 'g'),
(4, 1, 61, 'g'),
(4, 2197, 25, 'g'),
(4, 161, 94, 'g'),
(4, 137, 137, 'g'),
(6, 2381, 69, 'g'),
(6, 1155, 213, 'g'),
(6, 1159, 28, 'g'),
(8, 35, 137, 'ml'),
(8, 787, 227, 'g'),
(8, 633, 169, 'g'),
(10, 3599, 131, 'g'),
(10, 35, 149, 'ml'),
(10, 1155, 57, 'g'),
(10, 161, 52, 'g'),
(10, 131, 43, 'g'),
(10, 167, 87, 'g'),
(10, 1115, 145, 'g'),
(10, 115, 52, 'g'),
(12, 2969, 116, 'g'),
(12, 4653, 197, 'g'),
(12, 561, 128, 'g'),
(12, 7, 25, 'g'),
(14, 1841, 109, 'g'),
(14, 35, 145, 'ml'),
(14, 267, 23, 'g'),
(14, 813, 82, 'g'),
(14, 161, 169, 'g'),
(14, 7, 157, 'g'),
(14, 4653, 229, 'g'),
(16, 813, 139, 'g'),
(16, 7, 103, 'g'),
(18, 987, 202, 'g'),
(18, 1155, 120, 'g'),
(20, 1247, 261, 'g'),
(20, 1, 7, 'g'),
(20, 121, 92, 'g'),
(20, 161, 246, 'g'),
(20, 137, 20, 'g'),
(20, 1159, 146, 'g'),
(22, 835, 100, 'g'),
(22, 1159, 46, 'g'),
(22, 1155, 3, 'g'),
(24, 1655, 39, 'g'),
(24, 161, 206, 'g'),
(24, 2969, 92, 'g'),
(24, 7, 74, 'g'),
(24, 19, 56, 'g'),
(24, 1, 68, 'g'),
(24, 1587, 204, 'g'),
(26, 3599, 87, 'g'),
(26, 1159, 77, 'g'),
(26, 161, 44, 'g'),
(26, 1, 5, 'g'),
(26, 35, 113, 'ml'),
(26, 4653, 202, 'g'),
(26, 1155, 23, 'g'),
(26, 167, 50, 'g'),
(26, 1115, 101, 'g'),
(28, 4653, 144, 'g'),
(28, 1155, 199, 'g'),
(28, 19, 187, 'g'),
(28, 167, 101, 'g'),
(28, 131, 4, 'g'),
(30, 115, 184, 'g'),
(30, 117, 80, 'g'),
(30, 131, 11, 'g'),
(32, 2181, 32, 'g'),
(32, 1159, 110, 'g'),
(32, 633, 204, 'g'),
(34, 115, 136, 'g'),
(34, 1155, 92, 'g'),
(34, 813, 93, 'g'),
(34, 1, 8, 'g'),
(36, 1, 29, 'g'),
(36, 161, 63, 'g'),
(36, 137, 60, 'g'),
(36, 2077, 16, 'g'),
(36, 633, 203, 'g'),
(36, 1587, 181, 'g'),
(38, 35, 187, 'ml'),
(38, 4653, 220, 'g'),
(38, 115, 129, 'g'),
(38, 131, 8, 'g'),
(38, 167, 100, 'g'),
(38, 161, 290, 'g'),
(38, 137, 191, 'g'),
(38, 813, 0, 'g'),
(40, 1159, 215, 'g'),
(40, 2461, 67, 'g'),
(40, 1155, 203, 'g'),
(42, 1365, 274, 'g'),
(42, 1391, 11, 'g'),
(42, 1303, 263, 'g'),
(44, 745, 176, 'g'),
(44, 1365, 186, 'g'),
(44, 3809, 25, 'g'),
(44, 267, 37, 'g'),
(44, 1159, 66, 'g'),
(44, 161, 72, 'g'),
(44, 633, 182, 'g'),
(44, 131, 87, 'g'),
(44, 115, 153, 'g'),
(46, 745, 233, 'g'),
(46, 1365, 106, 'g'),
(48, 745, 70, 'g'),
(48, 115, 169, 'g'),
(50, 745, 68, 'g'),
(50, 117, 135, 'g'),
(50, 115, 96, 'g'),
(50, 131, 79, 'g'),
(50, 1159, 281, 'g'),
(52, 745, 274, 'g'),
(52, 35, 197, 'ml'),
(52, 1155, 245, 'g'),
(54, 787, 139, 'g'),
(54, 763, 174, 'g'),
(56, 745, 210, 'g'),
(56, 1049, 235, 'g'),
(56, 987, 86, 'g'),
(56, 931, 39, 'g'),
(58, 745, 171, 'g'),
(58, 1159, 14, 'g'),
(60, 763, 87, 'g'),
(60, 1115, 31, 'g'),
(60, 2265, 51, 'g'),
(60, 745, 131, 'g'),
(60, 115, 179, 'g'),
(62, 3001, 146, 'g'),
(62, 1239, 2, 'g'),
(64, 1239, 231, 'g'),
(64, 931, 217, 'g'),
(66, 1239, 253, 'g'),
(66, 1159, 58, 'g'),
(66, 931, 27, 'g'),
(68, 1247, 209, 'g'),
(68, 2227, 15, 'g'),
(68, 1, 36, 'g'),
(70, 931, 241, 'g'),
(70, 943, 59, 'g'),
(70, 987, 220, 'g'),
(70, 1159, 38, 'g'),
(70, 1155, 206, 'g'),
(72, 3207, 147, 'g'),
(72, 1, 16, 'g'),
(72, 1155, 75, 'g'),
(72, 131, 27, 'g'),
(72, 35, 200, 'ml'),
(72, 167, 47, 'g'),
(74, 71, 206, 'g'),
(74, 1155, 110, 'g'),
(74, 1159, 199, 'g'),
(74, 163, 24, 'g'),
(74, 2975, 7, 'g'),
(74, 787, 168, 'g'),
(76, 35, 152, 'ml'),
(76, 1155, 119, 'g'),
(76, 167, 151, 'g'),
(76, 3335, 50, 'g'),
(78, 115, 132, 'g'),
(78, 131, 12, 'g'),
(78, 1155, 138, 'g'),
(80, 781, 168, 'g'),
(80, 787, 174, 'g'),
(80, 35, 225, 'ml'),
(80, 1155, 14, 'g'),
(82, 4653, 214, 'g'),
(82, 3001, 56, 'g'),
(82, 7, 121, 'g'),
(82, 161, 98, 'g'),
(82, 137, 89, 'g'),
(84, 3001, 172, 'g'),
(84, 813, 10, 'g'),
(84, 1, 41, 'g'),
(84, 787, 5, 'g'),
(84, 7, 56, 'g'),
(86, 4653, 234, 'g'),
(86, 3001, 158, 'g'),
(86, 7, 137, 'g'),
(86, 327, 0, 'g'),
(86, 1841, 168, 'g'),
(88, 3647, 27, 'g'),
(88, 35, 64, 'ml'),
(90, 1, 53, 'g'),
(90, 745, 33, 'g'),
(90, 4653, 181, 'g'),
(90, 1155, 45, 'g'),
(90, 161, 173, 'g'),
(90, 35, 214, 'ml'),
(90, 167, 105, 'g'),
(90, 131, 22, 'g'),
(92, 745, 224, 'g'),
(92, 1159, 30, 'g'),
(92, 1155, 10, 'g'),
(92, 1115, 129, 'g'),
(92, 115, 164, 'g'),
(94, 1049, 136, 'g'),
(94, 745, 226, 'g'),
(94, 115, 142, 'g'),
(94, 131, 36, 'g'),
(94, 1115, 124, 'g'),
(94, 931, 51, 'g'),
(94, 987, 175, 'g'),
(96, 553, 67, 'g'),
(98, 835, 219, 'g'),
(98, 1155, 160, 'g'),
(100, 4653, 122, 'g'),
(100, 1155, 122, 'g'),
(100, 161, 164, 'g'),
(100, 131, 58, 'g'),
(100, 167, 202, 'g'),
(100, 35, 241, 'ml'),
(102, 4653, 28, 'g'),
(102, 1155, 23, 'g'),
(102, 161, 265, 'g'),
(102, 131, 15, 'g'),
(102, 167, 2, 'g'),
(102, 35, 142, 'ml')